name: Golang CF Scanning

on:
  workflow_dispatch: # Tombol manual untuk menjalankan workflow
  schedule:
    - cron: '0 */12 * * *' # Jalan otomatis tiap 12 jam

jobs:
  scan-proxies:
    runs-on: ubuntu-latest
    name: ğŸ” Scan Proxy Go

    steps:
    - name: ğŸ“‚ Checkout Repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GIT_TOKEN }} # Pastikan kamu sudah set Secret GIT_TOKEN di Settings Repo

    - name: ğŸ› ï¸ Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.25'

    - name: ğŸš€ Run Scanner
      run: |
        go run main.go

    - name: ğŸ“¤ Commit Results
      if: success()
      run: |
        git config --global user.name "Github Actions"
        git config --global user.email "actions@github.com"
        git add Data/alive.txt Data/Country-ALIVE.txt
        git commit -m "ğŸ” Update Proxy: alive.txt & Country-ALIVE.txt" || echo "No changes to commit"
        git push origin main
